#!/usr/bin/python
import subprocess
import re
import os
import datetime
respace=re.compile(r'\s+')
cmd="free"
sub_cmd=subprocess.Popen(cmd,stdout=subprocess.PIPE,shell=True).communicate()[0].split('\n')
ram_details=sub_cmd
print (ram_details)
remos=re.sub(respace," ",ram_details).split(' ')
print (remos)
totalram=remos[1]
usedram=remos[2]
freeram=remos[3]
print (float(freeram)/float(totalram))
total_free_perce=(float(freeram)*100/float(totalram))
print (total_free_perce)
if (total_free_perce < 90):
        print( "Memory utilization threshold and below are process consuming most of memory")
        cmd_mum="pa axo %mem,user,pid,command|sort -k1 -nr | head -10"
        print (subprocess.Popen(cmd_mum,stdout=subprocess.PIPE,shell=True).communicate()[0])
else:
        print ("memory utilization below thereshold no issue")
